// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartRentalPlatform.Infrastructure.Persistence;

#nullable disable

namespace SmartRentalPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521141057_AdminApprovalEnhancements")]
    partial class AdminApprovalEnhancements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.AdminApproval.ApprovalAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId", "CreatedAt");

                    b.HasIndex("ApprovalType", "EntityId");

                    b.ToTable("approval_audit_logs", "admin_approval");
                });

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.AdminApproval.KYCVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DateOfBirth")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FaceImageObjectKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FaceMatchScore")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IdImageObjectKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IdNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LivenessScore")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("kyc_verifications", "admin_approval");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeee0001"),
                            Address = "456 Lê Lợi, Quận 1, TP.HCM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = "1998-05-15",
                            FaceImageObjectKey = "kyc/tenant-kyc/face.jpg",
                            FullName = "Nguyễn Văn Tenant KYC",
                            IdImageObjectKey = "kyc/tenant-kyc/id-front.jpg",
                            IdNumber = "079098001234",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0003")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeee0002"),
                            Address = "789 Nguyễn Huệ, Quận 1, TP.HCM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = "1985-11-20",
                            FaceImageObjectKey = "kyc/landlord-kyc/face.jpg",
                            FullName = "Trần Thị Landlord KYC",
                            IdImageObjectKey = "kyc/landlord-kyc/id-front.jpg",
                            IdNumber = "079085009876",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0005")
                        });
                });

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.AdminApproval.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Area")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("RoomingHouseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("RoomingHouseId");

                    b.HasIndex("Status");

                    b.ToTable("rooms", "admin_approval");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccc0001"),
                            Area = 25m,
                            Capacity = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 2000000m,
                            RoomNumber = "A101",
                            RoomingHouseId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbb0001"),
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccc0002"),
                            Area = 28m,
                            Capacity = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 2500000m,
                            RoomNumber = "A102",
                            RoomingHouseId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbb0001"),
                            Status = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.AdminApproval.RoomImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("room_images", "admin_approval");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffff0002"),
                            ObjectKey = "rooms/a101/gallery-1.jpg",
                            RoomId = new Guid("cccccccc-cccc-cccc-cccc-cccccccc0001"),
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.AdminApproval.RoomPriceTier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MonthlyPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("OccupantCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "OccupantCount")
                        .IsUnique();

                    b.ToTable("room_price_tiers", "admin_approval");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddd0001"),
                            MonthlyPrice = 2000000m,
                            OccupantCount = 1,
                            RoomId = new Guid("cccccccc-cccc-cccc-cccc-cccccccc0001")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddd0002"),
                            MonthlyPrice = 2900000m,
                            OccupantCount = 2,
                            RoomId = new Guid("cccccccc-cccc-cccc-cccc-cccccccc0001")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddd0003"),
                            MonthlyPrice = 3600000m,
                            OccupantCount = 3,
                            RoomId = new Guid("cccccccc-cccc-cccc-cccc-cccccccc0001")
                        });
                });

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.AdminApproval.RoomingHouse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Amenities")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ApprovalStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("LandlordUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStatus");

                    b.HasIndex("LandlordUserId");

                    b.HasIndex("Visibility");

                    b.ToTable("rooming_houses", "admin_approval");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbb0001"),
                            Address = "123 Đường An Bình, Quận 7, TP.HCM",
                            Amenities = "Wifi,Giữ xe,Máy lạnh,Nước nóng",
                            ApprovalStatus = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Khu trọ yên tĩnh, tiện nghi cơ bản — Peaceful boarding area (Interval 1 seed)",
                            LandlordUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0004"),
                            Name = "Khu trọ An Bình",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Visibility = 1
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbb0002"),
                            Address = "88 Đường Test, Quận 10, TP.HCM",
                            Amenities = "Wifi,Thang máy",
                            ApprovalStatus = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Seed pending — duyệt để test cấp role Landlord",
                            LandlordUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0005"),
                            Name = "Khu trọ Chờ Duyệt (Landlord KYC)",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Visibility = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbb0003"),
                            Address = "99 Hidden St",
                            ApprovalStatus = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LandlordUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0004"),
                            Name = "Nhà Pending (không hiện public)",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Visibility = 0
                        });
                });

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.AdminApproval.RoomingHouseImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RoomingHouseId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomingHouseId");

                    b.ToTable("rooming_house_images", "admin_approval");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffff0001"),
                            IsCover = true,
                            ObjectKey = "rooming-houses/an-binh/cover.jpg",
                            RoomingHouseId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbb0001"),
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quản trị hệ thống / System administrator",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Người thuê (mặc định) / Default tenant role",
                            Name = "Tenant"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chủ trọ / Property owner",
                            Name = "Landlord"
                        });
                });

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarObjectKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AvatarSource")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailComfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutEndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OnboardingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("PhoneConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0001"),
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Admin",
                            Email = "admin@gmail.com",
                            EmailComfirmed = true,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            OnboardingStatus = "Completed",
                            PasswordHash = "AQAAAAEAACcQAAAAEDgWBHiZ1iPUyxiEv7MBd9JJW2brX/EpWwEcRPTwOBNPrPLjzXBpYfgGGA+xSqHPvQ==",
                            PhoneConfirmed = false,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0002"),
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Tenant Done",
                            Email = "tenant.done@gmail.com",
                            EmailComfirmed = true,
                            NormalizedEmail = "TENANT.DONE@GMAIL.COM",
                            OnboardingStatus = "Completed",
                            PasswordHash = "AQAAAAEAACcQAAAAEDgWBHiZ1iPUyxiEv7MBd9JJW2brX/EpWwEcRPTwOBNPrPLjzXBpYfgGGA+xSqHPvQ==",
                            PhoneConfirmed = false,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0003"),
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Tenant KYC",
                            Email = "tenant.kyc@gmail.com",
                            EmailComfirmed = true,
                            NormalizedEmail = "TENANT.KYC@GMAIL.COM",
                            OnboardingStatus = "NeedKyc",
                            PasswordHash = "AQAAAAEAACcQAAAAEDgWBHiZ1iPUyxiEv7MBd9JJW2brX/EpWwEcRPTwOBNPrPLjzXBpYfgGGA+xSqHPvQ==",
                            PhoneConfirmed = false,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0004"),
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Landlord Done",
                            Email = "landlord.done@gmail.com",
                            EmailComfirmed = true,
                            NormalizedEmail = "LANDLORD.DONE@GMAIL.COM",
                            OnboardingStatus = "Completed",
                            PasswordHash = "AQAAAAEAACcQAAAAEDgWBHiZ1iPUyxiEv7MBd9JJW2brX/EpWwEcRPTwOBNPrPLjzXBpYfgGGA+xSqHPvQ==",
                            PhoneConfirmed = false,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0005"),
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Landlord KYC",
                            Email = "landlord.kyc@gmail.com",
                            EmailComfirmed = true,
                            NormalizedEmail = "LANDLORD.KYC@GMAIL.COM",
                            OnboardingStatus = "NeedKyc",
                            PasswordHash = "AQAAAAEAACcQAAAAEDgWBHiZ1iPUyxiEv7MBd9JJW2brX/EpWwEcRPTwOBNPrPLjzXBpYfgGGA+xSqHPvQ==",
                            PhoneConfirmed = false,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ward")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0001"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0002"),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0003"),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0004"),
                            RoleId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.AdminApproval.Room", b =>
                {
                    b.HasOne("SmartRentalPlatform.Domain.Entities.AdminApproval.RoomingHouse", "RoomingHouse")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomingHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomingHouse");
                });

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.AdminApproval.RoomImage", b =>
                {
                    b.HasOne("SmartRentalPlatform.Domain.Entities.AdminApproval.Room", "Room")
                        .WithMany("Images")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.AdminApproval.RoomPriceTier", b =>
                {
                    b.HasOne("SmartRentalPlatform.Domain.Entities.AdminApproval.Room", "Room")
                        .WithMany("PriceTiers")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.AdminApproval.RoomingHouseImage", b =>
                {
                    b.HasOne("SmartRentalPlatform.Domain.Entities.AdminApproval.RoomingHouse", "RoomingHouse")
                        .WithMany("Images")
                        .HasForeignKey("RoomingHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomingHouse");
                });

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("SmartRentalPlatform.Domain.Entities.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("SmartRentalPlatform.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("SmartRentalPlatform.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRentalPlatform.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.AdminApproval.Room", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("PriceTiers");
                });

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.AdminApproval.RoomingHouse", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SmartRentalPlatform.Domain.Entities.User", b =>
                {
                    b.Navigation("UserProfile");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
